### PR TITLE
Use updated symbola web fonts

### PR DESCRIPTION
**Pull request by ajhyndman**
Working with fonts found here:

@laughinghan informed me that George Douros had updated the official versions of Symbola.  I found what seems to be those new, hinted webfonts here:

http://www.fonts2u.com/symbola.font

Based on that premise, I've put together a branch updating the fonts used in Mathquill to these new versions.

Noteworthy differences:

* The new font files are an order of magnitude smaller.  The SVG file for instance, has shrunk from 2.2 MB to 67 KB.
* The Square Root glyph appears to be completely different size and positioning, so I had to re-jig the CSS to restore previous behaviour.

### CODE REVIEW

**Comment by laughinghan** [comment]
> The SVG file for instance, has shrunk from 2.2 MB to 67 KB.

Holy crap

**Comment by laughinghan** [comment]
What tool did you use to generate the new files, or did they all come from fonts2u? (For reproducibility)

Also, it looks like your fix to the sqrt glyph is Chrome-only but breaks Firefox and IE11. The 3 successively taller square roots look great in Chrome:

evergreen_os_x_10 11_chrome

But break Firefox:

evergreen_linux_firefox

Previously:

prev_evergreen_linux_firefox

And break IE11:

pinned_windows_7_internet_explorer

Previously:

prev_pinned_windows_7_internet_explorer

You can find all the full screenshots in the CircleCI Artifacts tab in the `imgs/` folder: https://circleci.com/gh/mathquill/mathquill/284#artifacts

**Comment by ajhyndman** [comment]
@laughinghan I pulled the fonts directly from fonts2u.   I'm a bit upset that the fonts have different baselines in different formats.  Maybe it's preferable to generate our own versions of the eot and ttf files to improve consistency.  :(

**Comment by ajhyndman** [comment]
I pushed another version of .eot and .ttf files.  Lets see if it improves anything.

**Comment by ajhyndman** [comment]
It turns out, the font sizes were too good to be true.  These copies were missing glyphs.  👎 

I'm trying out font-squirrel's custom unicode subsetting features, working from the newest .ttf file from http://www.fonts2u.com/symbola.font.

**Comment by ajhyndman** [comment]
This looks comprehensive to me, but I'm not certain:

image

image

**Comment by ajhyndman** [comment]
Bad News:

* The fonts are not quite as small anymore
* The square root glyph still has whitespace at the top of the character

Good News:

* The fonts are still ~100kB instead of ~800kB
* The square root glyph css didn't need any changing

I think I've got all the glyphs that are actually used in these versions of the fonts.  Can you think of anything not tracked in the CI previews that we might want to watch out for?

**Comment by ajhyndman** [comment]
Bonus @laughinghan: Fixes #630.

**Comment by ajhyndman** [comment]
Okay... looking at #630, I realized that I'm still missing a bunch of glyphs!

I explicitly declared that the unicode range 2200-22FF should be included as well now.

http://www.fileformat.info/info/unicode/block/mathematical_operators/index.htm

image

Compare the `-demo.html` files from these two font versions:

https://drive.google.com/a/mathspace.com.au/file/d/0B6ArczcBSVqBUVQ0M3Y0aXFVaEE/view?usp=sharing

Have I got it right yet?  :(

**Comment by ajhyndman** [comment]
It still fixes #630!

image

**Comment by ajhyndman** [comment]
I added in the arrow range in unicode, and opted into Font Squirrel autohinting, after experimenting on my colleague's Linux machine.

image

**Comment by laughinghan** [comment]
@ajhyndman: Sweet, the broken square root rendering appears to be fixed.

The Google Drive link you posted appears to be password-protected, but, wanna see what I've been working on (instead of the stuff I probably should've been doing, like reviewing this PR)? https://many-worlds.gomix.me/mathquill/mathquill/pull/702/test/visual.html

Compare that side-by-side with: https://many-worlds.gomix.me/mathquill/mathquill/branch/master/test/visual.html

Try any other PR or branch or commit!

Anyway, this PR seems pretty close to mergeable. A few questions:
- any particular reason you got rid of the OTF format, it's just redundant?
- any particular reason to use the new `Symbola_hint.*` names instead of just `Symbola.*`?
- it's okay if you didn't do screenshots, but do you remember what kinds of things were improved on Linux by the Font Squirrel autohinting? Was it numerals, or symbols, or a command like square root or parens?

Also, there are a few regressions in some of the symbols I don't test in visual.html. There's a PR where someone added a page with a lot more symbols, I've pushed a branch off of that where I add these font files, look at them side-by-side:
- New Fonts: https://many-worlds.gomix.me/mathquill/mathquill/branch/all-amsmath-symbols-new-font/test/reference.html
- Old Fonts: https://many-worlds.gomix.me/mathquill/mathquill/pull/615/test/reference.html

Check out section 3.5, where `\beth`, `\mho`, `\Finv`, etc are (for me at least) falling back to a sans-serif system font, and in 3.18.2, `\mathbb{C}`/`\C`; also in 3.8, where `\gtrapprox`, `\gtreqqless`, etc are smaller than the other symbols (I think they're also fallback glyphs), and 3.10, where a similar thing happened to `\subseteqq`, `\supsetneqq`, etc. And, more subtle, but `\longleftarrow` and `\iff` in 3.9 are now heavier than the other arrows.

There's also improvements, like `\oslash`, and `\Cup`/`\Cap` from #630 of course, but also apparently `\leftrightharpoons` and `\rightleftharpoons` were swapped too.

**Comment by ajhyndman** [comment]
* _OTF_: Yeah, it's superfluous, and FontSquirrel doesn't generate it.  :D
* _Symbola_hint_: I used the name you get when you download the current version of the font.  I thought that might make it clearer where it came from.  Not important to me, of course.

The motivation was primarily targeted at the Chrome on Windows experience.  The most recent complaint was equals signs that were hard to read.

Here's a screenshot I did capture:

before:
image

after:
image

The instances I remember most were strictly vertical and horizontal bars.  A couple more specifics: +, -, and $.  Really small numerals got slightly better too, I seem to recall.

I'm not too surprised that there are a few regressions where glyphs are falling back to system fonts now.  Thanks for finding the branch.  I'll try to take a look and re-generate the files this week.

**Comment by ajhyndman** [comment]
Is that gomix page live-rendering the demo from any arbitrary commit?

**Comment by laughinghan** [comment]
> I'll try to take a look and re-generate the files this week.

Perfect, thanks! And yeah, I think I'd rather rename them back to just `Symbola.*`. I think this'll be ready to go then!

> Is that gomix page live-rendering the demo from any arbitrary commit?

Yup! :D (It won't work on really old commits because `make test` wasn't always the right build command, but it's a work in progress.)

**Comment by ajhyndman** [comment]
Okay, I've regenerated the fonts!  I went through the demo AMS Math page and added the entire unicode range for each symbol group that I found that wasn't already represented.

image

**Comment by laughinghan** [comment]
Beautiful! You missed one though&mdash;long arrows! (Section 3.9.) Most of them aren't that important, but `\implies` and `\iff` are pretty important.

Thought I'd take a look at the Unicode blocks, based on [their names](http://www.fileformat.info/info/unicode/block/index.htm) let's add these too:
- 27C0-27EF "Miscellaneous Mathematical Symbols A" (symbols for long division and true/false among others)
- 27F0-27FF "Supplemental Arrows-A" (this is the one with `\iff` and `\implies`)
- 2900-297F "Supplemental Arrows-B" (half-arrow "harpoons" like chemical equilibrium)
- 2980-29FF "Miscellaneous Mathematical Symbols-B" (this has the triple-vertical bar symbol for congruence you wanted)

These can be joined together and with the 2A00-2AFF that you already have, to be 27C0-27FF,2900-2AFF.

Also I'm curious&mdash;what is that single symbol you have and why didn't you do its whole block? Is it from the useless Dingbats block or something? Haha

By the way THANK YOU so much!

**Comment by ajhyndman** [comment]
Haha, I should be bowing and scraping in gratitude to you guys!  It's amazing how much a "thank you" can mean to us mortals, though.  :)

The single symbol is `\u23D0`, from the [Miscellaneous Technical block](https://unicode-table.com/en/blocks/miscellaneous-technical/).  It's used in *3.14 Nonpairing extensible symbols*.  I couldn't spot any of the others from that block in use.
(update: I just realised that `\u23AA` is also used, in the same section!)

I appreciate you reviewing so thoroughly.  I wouldn't have known where to start to attempt to assess glyph completeness.  Of course, we could have just punted and included everything, but we get a huge win in file-size by doing this.

Latest settings:

image

image

**Pull request merged**
