### PR TITLE
Enabled autoscroll for API-calls cmd and write

### PR DESCRIPTION
**Pull request by FWennerdahl**
When calling public API methods cmd and write the automatic horizontal scroll is not enabled, causing overflowing input to remain hidden for editors that have a defined max width.

Calling `controller.scrollHoriz()`after input has been added solves this.

### CODE REVIEW

**Comment by laughinghan** [comment]
Woah, really good point. Can we also add tests for this?

**Comment by FWennerdahl** [comment]
Tests added.

**Comment by robinwassen** [comment]
@laughinghan - What is the status on merging this?

**Comment by laughinghan** [comment]
Whoops, closed by GitHub when I deleted the `dev` branch, but this was really good work, re-opened as #519.

**Pull request closed without merging**
