### PR TITLE
Move integral from advancedSymbols to commands.

### PR DESCRIPTION
**Pull request by jwmerrill**
This is where sums and products are, and I think it makes sense to keep them together.

### CODE REVIEW

**Comment by laughinghan** [comment]
hmm, it _is_ just a symbol, is the funny thing with moving it out of `advancedSymbols.js` (unless it should gonna start coming with lower/upper limits too? Although I guess being in a `<big>` is different too). Do you need it in MathQuill-Basic or something?

**Comment by jwmerrill** [comment]
> Do you need it in MathQuill-Basic or something?

Yes.

**Comment by laughinghan** [comment]
That's fine I guess +1

**Comment by jwmerrill** [comment]
I'd be happy to move it into basicSymbols instead if you prefer.

**Comment by laughinghan** [comment]
Don't really care, just want to record why

**Pull request merged**
