### PR TITLE
Update README, add LICENSE

### PR DESCRIPTION
**Pull request by nedredmond**
Removed dead links from README and add LICENSE file for programmatic detection by github and other tools

### CODE REVIEW

**Comment by nedredmond** [comment]
@jaltekruse @jwmerrill no technical improvements, but helps the repo look less outdated!

**Review by jwmerrill — APPROVED** [review]

**Comment by jwmerrill** [comment]
@nedredmond are you able to merge this branch now that it's approved?

**Comment by nedredmond** [comment]
Nope! I can't merge anything!

**Comment by nedredmond** [comment]
@jwmerrill Nope! I can't merge anything!

**Comment by kschaefe** [comment]
I think only members can merge.  Doing so.

**Pull request merged**
