### PR TITLE
Change zero-width joiner to zero-width space because of wrong

### PR DESCRIPTION
**Pull request by karoltarasiuk**
rendering in Chrome v40.xxxxxx

### CODE REVIEW

**Comment by karoltarasiuk** [comment]
@laughinghan we noticed that in Chrome updated to v40.xx the cursor with &zwj; HTML entity produces thick black box. You can observe it both in

https://www.desmos.com/calculator
http://mathquill.com/

What is the purpose of using zero-width joiner? I noticed that when we replace it to zero-width space, it works fine, but I may not be aware of some other implications.

**Comment by laughinghan** [comment]
Oh thanks! Desmos was just running into this problem today. The zero-width space fix looks awesome, didn't know that existed, we're also looking into getting rid of the hack of having a zero-width character at all

**Comment by laughinghan** [comment]
Actually the [zero-width space](http://en.wikipedia.org/wiki/Zero-width_space) looks so awesome I might have to start using it in other places, like instead of the `<span style="display:inline-block;width:0">&nbsp;</span>`s in `Fraction`s, `SupSub`s, and `Binomial`s! I was just running into a problem where the non-breaking space is sticking out to the right invisibly, increasing the containing `.scrollWidth`

**Comment by karoltarasiuk** [comment]
Yeah, it looked good to me as well. It's just not supported by IE6 or lower, but I don't think anyone would ever care about those anymore. And indeed in some cases it's better than &nbsp;

**Comment by jwmerrill** [comment]
Awesome. Thanks so much for contributing this.

**Pull request merged**
